guests = ['Steve Jobs','Elon Musk','Godfred Mensah','Steve Wozniak','Robert Downey','NF','Cristiano Ronaldo']
print(f"\nAttention guests Bigger table found!!")
guests.insert(0,'Bill Gates')
guests.insert(4,'Fafa')
guests.append('Micheal Jordan')
print(f"Welcome {guests[0]}")
print(f"Welcome {guests[1]}")
print(f"Welcome {guests[2]}")
print(f"Welcome {guests[3]}")
print(f"Welcome {guests[4]}")
print(f"Welcome {guests[5]}")
print(f"Welcome {guests[6]}")
print(f"Welcome {guests[-2]}")
print(f"Welcome {guests[-1]}")